environment:
  matrix:
    # https://www.appveyor.com/docs/windows-images-software/#python
    # currently lxml does not successfully install in 3.5 and 3.8
#    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python37"
#    - PYTHON: "C:\\Python38"

build: off

test_script:
  - "%PYTHON%\\python.exe setup.py test"